[package]
name = "backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serial2 = "0.2.19"
opencv = "0.88"
windows = "0.52.0"

thiserror.workspace = true